version: 1.0.0.{build}

environment:
  CMAKE_PREFIX_PATH: "C:\\Qt\\5.5\\msvc2013_64"

platform: x64
configuration: Release

build:
  project: launcher.vcxproj

install:
  - git config --global url."https://github.com/".insteadOf "git@github.com:"
  - git submodule update --init --recursive
  - nuget install log4cxx

before_build:
  - echo Running cmake...
  - cmake -G "Visual Studio 12 Win64" -D Log4Cxx_LIBRARY="./log4cxx.0.10.0/lib" -D Log4Cxx_INCLUDE_DIR="./log4cxx.0.10.0"
