version: 1.0.0.{build}

platform: x64
configuration: Release

build:
  project: launcher.vcxproj

install:
  - git config --global url."https://".insteadOf git://
  - git submodule update --init --recursive

before_build:
  - echo Running cmake...
  - cmake -G "Visual Studio 12 Win64"
