#! /usr/bin/env bash

set -e

# Use sed to replace the SSH URL with the public URL, then initialize submodules
echo "-- Fetching submodules"
sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
git submodule update --init --recursive
sudo apt-get update -qq

echo "-- Installing dependencies..."
sudo apt-get install -y xorg-dev libglu1-mesa-dev libboost-all-dev libunittest++-dev liblog4cxx10 liblog4cxx10-dev

echo "-- Setting PKG_CONFIG_PATH"
export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/share/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:$PKG_CONFIG_PATH

echo "-- Installing Qt 5.4"
sudo add-apt-repository -y ppa:beineri/opt-qt541
sudo apt-get update -qq
sudo apt-get install -y qt54base
export CMAKE_PREFIX_PATH=/opt/qt54:$CMAKE_PREFIX_PATH

echo "-- Installing cmake 3.2.1"
cmake_url=http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.tar.gz
mkdir _cmake && cd $_ && wget $cmake_url -O - | tar zxf - --strip-components=1
sudo cp -R ./bin/* /usr/local/bin
sudo cp -R ./share/* /usr/local/share
cmake --version
