#! /usr/bin/env bash

set -e

if [[ $CI == "true" && $DRONE == "true" ]]; then
  # Use sed to replace the SSH URL with the public URL, then initialize submodules
  sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  git submodule update --init --recursive
  sudo apt-get update -qq
  sudo apt-get install -y xorg-dev libglu1-mesa-dev libboost-all-dev libunittest++-dev
fi

./configure
make rts
make check
